#!/usr/bin/env python3

class SingleLinkedNode:

    def __init__(self, value = '', next = None):
        self.value = value
        self.next = next

    def printList(self):
        """This function prints the list start at this node."""
        print(self.value)
        while(self.next != None):
            self = self.next
            print(self.value)

def test_single_linked_list():
    print("Creating a single linked list with 5 nodes!!")
    head = SingleLinkedNode(5)
    head_perm = head
    for i in range(0, 4):
        head.next = SingleLinkedNode((5 + (i+1)*5))
        head = head.next
    print("Printing the generate 5 node single linked list.")
    head_perm.printList()


if __name__ == "__main__":
    test_single_linked_list()        
